openapi: 3.1.0
info:
  title: Google Calendar and Meet API Integration
  description: API for managing Google Calendar events and Google Meet spaces.
  version: 1.0.0
servers:
  - url: https://c6a1-2407-d000-1a-f44b-8cab-70b3-fad9-71c6.ngrok-free.app
    description: Local development server
paths:
  /privacy:
    get:
      summary: Privacy Policy
      description: Returns the privacy policy text as an HTML page.
      operationId: getPrivacyPolicy
      responses:
        "200":
          description: Privacy policy HTML content.
          content:
            text/html:
              schema:
                type: string

  /startAuth:
    get:
      summary: Start OAuth Authentication
      description: Initiates the OAuth authentication flow.
      operationId: startOAuthFlow
      responses:
        "200":
          description: Authentication URL.
          content:
            application/json:
              schema:
                type: object
                properties:
                  auth_url:
                    type: string
                    format: uri

  /handleAuth:
    get:
      summary: Handle OAuth Callback
      description: Completes the OAuth authentication flow and stores user credentials.
      operationId: handleOAuthCallback
      responses:
        "200":
          description: Authentication successful message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /createEvent:
    post:
      summary: Create a Google Calendar Event
      description: Creates a new event in the user's Google Calendar.
      operationId: createCalendarEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Title of the event.
                start_time:
                  type: string
                  format: date-time
                  description: Start time of the event in ISO 8601 format.
                end_time:
                  type: string
                  format: date-time
                  description: End time of the event in ISO 8601 format.
                location:
                  type: string
                  description: Location of the event.
                description:
                  type: string
                  description: Description of the event.
      responses:
        "200":
          description: Event created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  event_link:
                    type: string
                    format: uri
        "400":
          description: Missing or invalid input parameters.
        "500":
          description: Internal server error.

  /getEvents:
    get:
      summary: Get Events on a Specific Date
      description: Fetches all events scheduled for a specific date from Google Calendar.
      operationId: getEventsByDate
      parameters:
        - name: date
          in: query
          required: true
          description: Date to fetch events for (format YYYY-MM-DD).
          schema:
            type: string
            format: date
      responses:
        "200":
          description: List of events for the specified date.
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        summary:
                          type: string
                        start:
                          type: object
                          properties:
                            dateTime:
                              type: string
                              format: date-time
                        end:
                          type: object
                          properties:
                            dateTime:
                              type: string
                              format: date-time
        "400":
          description: Invalid date parameter.
        "500":
          description: Internal server error.

  /updateEvent:
    put:
      summary: Update a Google Calendar Event
      description: Updates the details of an existing event by its ID.
      operationId: updateCalendarEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                event_id:
                  type: string
                  description: The ID of the event to update.
                title:
                  type: string
                  description: The new title of the event.
                start_time:
                  type: string
                  format: date-time
                  description: The new start time of the event.
                end_time:
                  type: string
                  format: date-time
                  description: The new end time of the event.
                location:
                  type: string
                  description: The new location of the event.
                description:
                  type: string
                  description: The new description of the event.
      responses:
        "200":
          description: Event updated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  event:
                    type: object
        "400":
          description: Missing or invalid event ID.
        "500":
          description: Internal server error.

  /createMeetingWithCalendar:
    post:
      summary: Create Google Meet Space and Add to Calendar
      description: >
        Creates a Google Meet meeting space using the Meet API and then adds the generated link
        to Google Calendar as an event with a specified title, date, and time.
      operationId: createMeetingWithCalendar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Title of the meeting space and calendar event.
                date:
                  type: string
                  format: date
                  description: Date of the event (format YYYY-MM-DD).
                time:
                  type: string
                  format: time
                  description: Start time of the event (format HH:MM:SS).
                participants:
                  type: array
                  items:
                    type: string
                    format: email
                  description: Optional list of participant email addresses.
      responses:
        "200":
          description: Meeting space and calendar event created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  meet_link:
                    type: string
                    format: uri
                    description: Link to the created Google Meet space.
                  calendar_event_link:
                    type: string
                    format: uri
                    description: Link to the created Google Calendar event.
        "400":
          description: Missing or invalid input parameters.
        "500":
          description: Internal server error.
